# Standing in school
FRESHMAN = 'FR'
SOPHOMORE = 'SO'
JUNIOR = 'JR'
SENIOR = 'SR'

# Majors
ACCOUNTING = 'ACCOUNTING'
ENTREPRENEURSHIP = 'ENTREPRENEURSHIP'
FINANCE = 'FINANCE'
MARKETING = 'MARKETING'
MANAGEMENT = 'MANAGEMENT'
MANAGEMENT_INFORMATION_SYSTEMS = 'MANAGEMENT INFORMATION SYSTEMS'
BUSINESS_UNDECIDED = 'BUSINESS UNDECIDED'
BUSINESS_OTHER = 'BUSINESS OTHER'
NON_BUSINESS = 'NON BUSINESS'
